// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateItemItemsPostData, CreateItemItemsPostErrors, CreateItemItemsPostResponses, ReadItemItemsItemIdGetData, ReadItemItemsItemIdGetErrors, ReadItemItemsItemIdGetResponses, ReadRootGetData, ReadRootGetResponses, UpdateItemItemsItemIdPutData, UpdateItemItemsItemIdPutErrors, UpdateItemItemsItemIdPutResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadRootGetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Read Item
 */
export const readItemItemsItemIdGet = <ThrowOnError extends boolean = false>(options: Options<ReadItemItemsItemIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<ReadItemItemsItemIdGetResponses, ReadItemItemsItemIdGetErrors, ThrowOnError>({
        url: '/items/{item_id}',
        ...options
    });
};

/**
 * Update Item
 */
export const updateItemItemsItemIdPut = <ThrowOnError extends boolean = false>(options: Options<UpdateItemItemsItemIdPutData, ThrowOnError>) => {
    return (options.client ?? client).put<UpdateItemItemsItemIdPutResponses, UpdateItemItemsItemIdPutErrors, ThrowOnError>({
        url: '/items/{item_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create Item
 */
export const createItemItemsPost = <ThrowOnError extends boolean = false>(options: Options<CreateItemItemsPostData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateItemItemsPostResponses, CreateItemItemsPostErrors, ThrowOnError>({
        url: '/items/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
