// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Item
 */
export type Item = {
    /**
     * Name
     */
    name: string;
    /**
     * Price
     */
    price: number;
    /**
     * Is Offer
     */
    is_offer?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadItemItemsItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: {
        /**
         * Q
         */
        q?: string | null;
    };
    url: '/items/{item_id}';
};

export type ReadItemItemsItemIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadItemItemsItemIdGetError = ReadItemItemsItemIdGetErrors[keyof ReadItemItemsItemIdGetErrors];

export type ReadItemItemsItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateItemItemsItemIdPutData = {
    body: Item;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: never;
    url: '/items/{item_id}';
};

export type UpdateItemItemsItemIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateItemItemsItemIdPutError = UpdateItemItemsItemIdPutErrors[keyof UpdateItemItemsItemIdPutErrors];

export type UpdateItemItemsItemIdPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateItemItemsPostData = {
    body: Item;
    path?: never;
    query?: never;
    url: '/items/';
};

export type CreateItemItemsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateItemItemsPostError = CreateItemItemsPostErrors[keyof CreateItemItemsPostErrors];

export type CreateItemItemsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
