[tool.poetry]
name = "llm"
version = "0.1.0"
description = "llm models"
authors = ["Domengo <dominicsengo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
